// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClqvQy7kq89rsyVp-QzokdpVAdkRp6p9s',
    appId: '1:328635602290:web:092ce4b00ebf4d13f8b9eb',
    messagingSenderId: '328635602290',
    projectId: 'pharmacare-2b107',
    authDomain: 'pharmacare-2b107.firebaseapp.com',
    storageBucket: 'pharmacare-2b107.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFmMhsQN_-LStcMCEGRQ84yNE68OYuvo',
    appId: '1:328635602290:android:3c55e80b30f565d4f8b9eb',
    messagingSenderId: '328635602290',
    projectId: 'pharmacare-2b107',
    storageBucket: 'pharmacare-2b107.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2g14uT5CzdwM5uwEYaO2ToiM3rw7lIVI',
    appId: '1:328635602290:ios:f3de06e24608a4e6f8b9eb',
    messagingSenderId: '328635602290',
    projectId: 'pharmacare-2b107',
    storageBucket: 'pharmacare-2b107.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2g14uT5CzdwM5uwEYaO2ToiM3rw7lIVI',
    appId: '1:328635602290:ios:f3de06e24608a4e6f8b9eb',
    messagingSenderId: '328635602290',
    projectId: 'pharmacare-2b107',
    storageBucket: 'pharmacare-2b107.firebasestorage.app',
    iosBundleId: 'com.example.pharmacare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClqvQy7kq89rsyVp-QzokdpVAdkRp6p9s',
    appId: '1:328635602290:web:f0e676e85deaa383f8b9eb',
    messagingSenderId: '328635602290',
    projectId: 'pharmacare-2b107',
    authDomain: 'pharmacare-2b107.firebaseapp.com',
    storageBucket: 'pharmacare-2b107.firebasestorage.app',
  );
}
